version: '2'
services:
  address_service:
    container_name: address-service
    build: ./services/address-service
    ports:
      - "8090:8090"

  # feature_service:
  #   container_name: feature-service
  #   build: ./services/feature-service
  #   ports:
  #     - "8091:8091"

  userservice:
    container_name: user-service
    build: ./services/user-service
    ports:
      - "8092:8092"

  graphqlservice:
    container_name: graphql-service
    build: ./services/graphql-service
    ports:
      - "4000:4000"
